theme: jekyll-theme-cayman

url: "https://username.github.io"
baseurl: ""

title: Ryan Conklin

description: A virtual proof that name is awesome!

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"